-- Create expenses table
CREATE TABLE public.expenses (
    expense_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    category TEXT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    description TEXT,
    receipt_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS and add Allow all policy
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON public.expenses FOR ALL USING (true);

-- Create payment_summaries table
CREATE TABLE public.payment_summaries (
    summary_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    total_amount DECIMAL(10, 2) NOT NULL,
    primary_method TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS and add Allow all policy
ALTER TABLE public.payment_summaries ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all" ON public.payment_summaries FOR ALL USING (true);
